-- ─── Ambassador Invite Codes ─────────────────────────────────────────────────
-- Generated by admin, shared with potential ambassadors to access the application page

CREATE TABLE IF NOT EXISTS ambassador_invites (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  city TEXT,                          -- optional: pre-assign to a city
  tier TEXT CHECK (tier IN ('explorer', 'trailblazer', 'pack_leader')),
  recipient_name TEXT,                -- who it was intended for
  recipient_email TEXT,               -- optional: lock to specific email
  max_uses INTEGER NOT NULL DEFAULT 1,
  times_used INTEGER NOT NULL DEFAULT 0,
  expires_at TIMESTAMPTZ,             -- optional expiry
  created_by TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  notes TEXT
);

-- ─── Ambassador Applications ─────────────────────────────────────────────────
-- Stores applications from the /ambassadors page (invite-only), reviewed by admin

CREATE TABLE IF NOT EXISTS ambassador_applications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Applicant info
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  instagram_handle TEXT,
  city TEXT NOT NULL,

  -- Application content
  why_join TEXT NOT NULL,
  how_explore TEXT NOT NULL,
  availability TEXT NOT NULL CHECK (availability IN ('explorer', 'trailblazer', 'pack_leader')),
  follower_count TEXT,

  -- Agreement
  agreement_accepted BOOLEAN NOT NULL DEFAULT false,
  agreement_accepted_at TIMESTAMPTZ,
  agreement_version TEXT DEFAULT '1.0',

  -- Processing
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'withdrawn')),
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  review_notes TEXT,

  -- Ambassador details (filled on approval)
  tier TEXT CHECK (tier IN ('explorer', 'trailblazer', 'pack_leader')),
  referral_code TEXT UNIQUE,
  badge_enabled BOOLEAN DEFAULT false,

  -- Invite tracking
  invite_code TEXT,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  ip_address TEXT,
  user_agent TEXT
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ambassador_invites_code ON ambassador_invites(code);
CREATE INDEX IF NOT EXISTS idx_ambassador_applications_status ON ambassador_applications(status);
CREATE INDEX IF NOT EXISTS idx_ambassador_applications_city ON ambassador_applications(city);
CREATE INDEX IF NOT EXISTS idx_ambassador_applications_email ON ambassador_applications(email);
CREATE INDEX IF NOT EXISTS idx_ambassador_applications_referral ON ambassador_applications(referral_code);
